sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t bchruslinski/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bchruslinski/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-916198988467"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY



